name: CD job for 3070

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  run_on_3070:

    runs-on: RTX 3070Ti Mobile

    steps:
    - uses: actions/checkout@v4

    - name: Put current date into a variable
      run:  $NOW=& Get-Date -format yyyy.MM.dd.hh.ss; echo "NOW=$NOW" >> $env:GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64
        tags: "${{ secrets.DOCKER_USER }}/gamac:${{env.NOW}}"