name: CI/CD job for 4090

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  DATA: OpenML_100-plants-margin_orig.csv
  TARGET_MEASURES: BR,OS,MCR,SYM

jobs:

  push_to_registry_4090:

    runs-on: RTX 4090
    outputs:
      date_tag: ${{ steps.get-date.outputs.date_tag }}
    steps:
    - uses: actions/checkout@v4

    - name: Put current date into a variable
      run:  $NOW=& Get-Date -format yyyy.MM.dd.hh.ss; echo "NOW=$NOW" >> $env:GITHUB_ENV

    - name: Put MinIO vars to env and download data from MinIO
      run: >-
        $path = (Get-Item .).FullName;
        $cert = "${{ secrets.MINIO_CERT }}";
        $cert | Out-File "${{ secrets.MINIO_CERT_PATH }}";
        $env:MINIO_ACCESS_KEY="${{ secrets.MINIO_ACCESS_KEY }}";
        $env:MINIO_SECRET_KEY="${{ secrets.MINIO_SECRET_KEY }}";
        $env:SSL_CERT_FILE=$path + '\' + '${{ secrets.MINIO_CERT_PATH }}';
        $env:MINIO_ENDPOINT="${{ secrets.MINIO_ENDPOINT }}";
        $env:DATA="${{ env.DATA }}";
        dir;
        pip install minio;
        python download_minio.py

    - name: Save tag
      id: get-date
      run: echo "date_tag=${{env.NOW}}" >> $env:GITHUB_OUTPUT

    - name: Check data
      run: cd test-data; dir

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64
        tags: "${{ secrets.DOCKER_USER }}/gamac:${{env.NOW}}"

  run_on_4090:
    needs: push_to_registry_4090
    runs-on: RTX 4090

    steps:
    - uses: actions/checkout@v4

    - name: Check date tag
      run: echo "${{ needs.push_to_registry_4090.outputs.date_tag }}"

    - name: Run docker container
      run: >-
          docker run
          --rm
          -i
          --gpus=all
          -e DATA="${{ env.DATA }}"
          -e TARGET_MEASURES="${{ env.TARGET_MEASURES }}"
          "${{ secrets.DOCKER_USER }}/gamac:${{ needs.push_to_registry_4090.outputs.date_tag }}"